from . import (
    meet_11_abertura,
    meet_12_ciencia,
    meet_13_fundamentos,
    meet_14_ipython,
    meet_15_bases,
    meet_16_manipulacao,
    meet_17_descoberta,
    meet_18_avaliacao,
    meet_21_amostragem,
    meet_22_estatistica,
    meet_23_visualizacao,
    meet_24_qualidade,
    meet_25_transformacao,
    meet_26_avaliacao,
    meet_31_aprendizado,
    meet_32_modelagem,
    meet_33_metricas,
    meet_34_outros,
    meet_35_avaliacao,
    meet_36_encerramento,
)

meets = [
    module.meet
    for module in (
        meet_11_abertura,
        meet_12_ciencia,
        meet_13_fundamentos,
        meet_14_ipython,
        meet_15_bases,
        meet_16_manipulacao,
        meet_17_descoberta,
        meet_18_avaliacao,
        meet_21_amostragem,
        meet_22_estatistica,
        meet_23_visualizacao,
        meet_24_qualidade,
        meet_25_transformacao,
        meet_26_avaliacao,
        meet_31_aprendizado,
        meet_32_modelagem,
        meet_33_metricas,
        meet_34_outros,
        meet_35_avaliacao,
        meet_36_encerramento,
    )
]
