name: Quarto publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.42
          tinytex: true

      - run: |
          ~/.TinyTeX/bin/x86_64-linux/tlmgr update --self
          ~/.TinyTeX/bin/x86_64-linux/tlmgr install hyphen-portuguese tex-gyre
      
      # - name: install texlive dependencies
      #   run: sudo apt -q install texlive-fonts-recommended texlive-lang-portuguese --ignore-missing

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: quarto render and publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
